name: MooContentAssist
author: NKjoep
category: Forms
tags: [forms, interface, calculator, cells, validator]
docs: https://github.com/NKjoep/MooCells/
demo: http://nkjoep.github.com/MooCells/
current: 0.26